---
- name: MetricbeatPlaybook
  hosts: webservers
  become: true
  tasks:

  - name: curl metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metic beat
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Metricbeat module enable
    command: metricbeat modules enable docker 

  - name: Configure metricbeat system modules
    command: metricbeat setup 
   
  - name: metricbeat start
    command: service metricbeat start

  - name: Enable metricbeat service
    systemd:
      name: metricbeat
      enabled: yes
