---
- name: My first playbook
  hosts: webservers
  become: true
  tasks:

  - name: Install docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install python3-pip
    apt:
       force_apt_get: yes
       name: python3-pip
       state: present

  - name: Install Docker Python Module
    pip:
      name: docker
      state: present

  - name: dvwa
    docker_container:
       name: DVWA
       image: cyberxsecurity/dvwa:latest
       state: started
       restart_policy: always
       published_ports: 80:80

  - name: Enable docker servivce
    systemd:
      name: docker
      enabled: yes
